language: java
jdk:
  - oraclejdk8
env:
  - env=ci
  
after_failure:
  - cat build/test-results/TEST-au.csiro.casda.access.soda.AsyncFunctionalTest.xml
  - cat build/test-results/TEST-au.csiro.casda.access.soda.AccessDataControllerTest$GetJobTest.xml
  - cat build/test-results/TEST-au.csiro.casda.access.services.InlineScriptServiceTest.xml